### ISSUE TITLE
Being able to manipulate blocks in unfocused mouse mode.

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#103]
## Describe the bug
You are able to manipulate blocks while being in unlocked mouse mode.

## To Reproduce
1. Focus debug menu (Esc to unlock the mouse)
2. Click on anything and you will be able to manipulate blocks while not having the camera be focused.

## Expected behavior
It should not allow you to place or remove blocks while in unlocked mouse mode.

**Comment by tobyplowy** [comment]
Video showing the big https://youtu.be/txZI_P3NBDo

**Comment by beeperdeeper089** [comment]
Ah yes, I will fix this as soon as my layer stack is in.
