### ISSUE TITLE
Crash when breaking a block outside grass chunk.

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#104]
## Describe the bug
I get a crash when breaking a block in the area above the grass chunk. (Exception massage below) It does not happen if you remove blocks inside the grass chunk itself. (Even when placed)
(If you place and remove multiple blocks it's fine just don't remove the first block that you place as that is the one that crashes.)

## To Reproduce
1. Place a block in the air area (Above the grass)
2. Remove the block and you get an Instant crash (It only works with the first block that you place if you place multiple blocks)

## Additional context
Exception thrown at 0x08B9FE35 in Phoenix.exe: 0xC0000005: Access violation reading location 0x00000000.
And this may also be useful?
![image](https://user-images.githubusercontent.com/16853304/73620070-7b589980-4630-11ea-90c0-cd454b1d4799.png)

**Comment by apachano** [comment]
Hmm, :/ let's try to get repro steps, otherwise, there isn't anything we can really do to fix this.

**Comment by tobyplowy** [comment]
Got it again. I think it happened because of the missing texture block.

**Comment by tobyplowy** [comment]
Here's a video of me performing the crash.
Again this happens at complete random. (Sometimes it crashes and sometimes it does not)
https://youtu.be/oIWXKPQ3gcg

**Comment by tobyplowy** [comment]
Now it seems to always happen...

**Comment by tobyplowy** [comment]
Oh it only seems to happen if the block is outside (on top of) the grass chunk (In the air area)

**Comment by tobyplowy** [comment]
@apachano I found the problem and I updated my issue to be more descriptive.

**Comment by tobyplowy** [comment]
If you place multiple blocks and remove them it's fine but as soon as you remove the first block that you placed it crashes. So it's only the first block that you place that crashes.

**Comment by beeperdeeper089** [comment]
That is one funky bug...

**Comment by tobyplowy** [comment]
It sure is. Very interesting and specific.

**Comment by tobyplowy** [comment]
#109 May be related to this crash.
