### ISSUE TITLE
Crash when breaking last block in a chunk

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#109]
## Describe the bug
I get a crash when I break all of the grass blocks in a chunk.
As soon as the last block is broken it crashes. #104 May be related to this.
Doing this also gives me an exception message tho it does not seem to be the same as #104

The message that I get for this crash.
Exception thrown at 0x08DBFE35 in Phoenix.exe: 0xC0000005: Access violation reading location 0x00000000.

## To Reproduce
1. Remove all blocks in a chunk by hand. (Tip use the chunk walls as a guide)
2. Remove the last remaining block of the chunk.
3. Crash!

## Expected behavior
It should not crash when you remove all blocks in a chunk.

## Additional context
Yes I actually removed all blocks in a chunk 4 times now. BY HAND! And all of that just to debug =D
I love this stuff (Not joking)

**Comment by beeperdeeper089** [comment]
That is very funky. I'm not sure why this would even be an issue, thanks for the report!
