### ISSUE TITLE
Basic player API

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#116]
## Story
We need to expose the player to the LUA API

## MVP
What are the minimum features needed for this story?
- [x] Function to set player position
- [x] Function to set player speed
- [ ] Function to set the block in the player's hand

**Comment by tobyplowy** [comment]
Maybe adding a new /tp command for the terminal would be nice.

**Comment by apachano** [comment]
Should we hardcode that or make it a module?

**Comment by tobyplowy** [comment]
I think hard codeing it would be a good idea seeing as it's a very basic command and it's a thing that gets used a LOT. It's pretty much a MUST have.
