### ISSUE TITLE
Implement message transmission

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#148]
## Story
Currently, when a command is typed into the terminal the client responds to that. We want all content typed into the terminal to be sent directly to the server.

## MVP
What are the minimum features needed for this story?
-  [x] All content typed into the terminal gets sent to the server
-  [x] The client networking connection can write to the terminal
-  [x] The server handles and executes commands in response to receiving a message from the client

## Stretch
What are some non-required features for this story?
-  [ ] The print command in Lua has an added specifier for which player/ player group the message is sent to

**Comment by tobyplowy** [comment]
@apachano @beeperdeeper089 Done?
If so can one of you open an issue for the stretch goal and close the issue?

**Comment by beeperdeeper089** [comment]
I'd wait for Austin on this one, I'd say close this once it's merged into develop

**Comment by apachano** [comment]
+1 once it hits develop its done.
