### ISSUE TITLE
Send voxel world to client

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#149]
## Story
When a client connects, it should get the state of the chunks around the player, when the player moves the client should get new chunks.

## MVP
What are the minimum features needed for this story?
- [ ] On first connection, n chunks around the player are transmitted to the client.
- [x] When the player moves into a new chunk, new chunks are sent to the client

**Comment by tobyplowy** [comment]
@apachano I think it would be much better if you only send relevant data and not the entire word?
So only the chunks/metadata that the player needs at that time? That way you are not sending and receiving gigs of data in one go. (Just thinking out loud)

**Comment by beeperdeeper089** [comment]
I second that, let's only send what needs to be sent.

From personal experience a server with 20-30 people exploring the world can result in a shit load of chunks which is a lot of data

**Comment by apachano** [comment]
Updated, IDK what I was thinking when I typed this. Maybe MVP?
