### ISSUE TITLE
Send voxel events to client

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#150]
## Story
When something in the voxel world changes, we should send an event to the client letting them know.

## MVP
What are the minimum features needed for this story?
-  [ ] Timestamped voxel events are generated and sent to the client
-  [ ] Client updates based on timestamped event

**Comment by SuperFola** [comment]
The timestamp should be relative to the number of ticks sent by the server, not relative to the standard unix timestamp right?

**Comment by apachano** [comment]
@SuperFola Yes, it will be interesting to sync the client and server up appropriately but for now basic sequencing and timing how quickly each end can transmit will be sufficient.x

**Comment by apachano** [comment]
Closing as we are abandoning networking for the time being
