### ISSUE TITLE
Should have an error message when no save is found / when Mods.txt is missing

### ISSUE THREAD

**Issue by SuperFola** [GentenStudios/Phoenix#188]
## Describe the bug
The world is empty when those things aren't found.

## To Reproduce
1. Clear the Saves/ folder
2. Play

## Expected behavior
A nice error message when no save is found / the Mods.txt is missing

**Comment by tobyplowy** [comment]
Seems like this no longer has any issues. It just makes a new save/Mods.txt if no save/Mods.txt is present. Tho it still doesn't log a message so resolved for now? (We can add the message later seeing as the launcher is a future thing anyways) @apachano Ping!

**Comment by apachano** [comment]
IMO the intended behavior should be to create a new save if none exists so I would argue that this is resolved.

**Comment by tobyplowy** [comment]
@apachano Agreed!
