### ISSUE TITLE
In game terminal

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#19]
## Story
In order to execute commands, the game needs a built-in terminal that accepts input and outputs.

## MVP
What are the minimum features needed for this story?
- [ ] Pressing the enter key brings up edit field and output box
- [x] Output from a stream is displayed above edit field similar to a terminal
- [x] Hitting return sends the contents of the edit field to a stream
- [ ] When in edit mode scrolling scrolls back the history of the output display

## Stretch
What are some non-required features for this story?
- [x] The output still displays but with no background and less scrollback when the edit box is not focused
- [ ] Text highlighting is possible in the output window
- [ ] Terminal history recall

**Comment by M3TIOR** [comment]
I'm working on this rn & have been for the last few days. Assign me to the job pleeez! :blue_heart:

**Comment by tobyplowy** [comment]
@M3TIOR It has been done.
Glad to have you on this and good luck :)

**Comment by M3TIOR** [comment]
@apachano what kind of highlighting were you thinking? As in: automated highlighting, or user directed / selection type highlighting?

**Comment by apachano** [comment]
@M3TIOR I was thinking ANSI escape code compatibility is all, from there the program can handle the rest. That will also make it compatible with the terminal when executing commands via the server.

**Comment by M3TIOR** [comment]
Okay thank god, that's what I thought you meant and what I started adding scaffolding for, but just wanted to make sure. Thx! :+1: :smiley:

**Comment by M3TIOR** [comment]
Also what do you mean by "edit mode"?

**Comment by apachano** [comment]
"edit mode" is when the cursor is focused on the input field. In terms of the MVP this is when the terminal is visible.

**Comment by M3TIOR** [comment]
Okay, good, we're on the same page then. From the way you initially said it, it sounded like maybe you were talking about terminal history recall, but that's not really an extremely useful feature atm. Just wanted to make sure.

**Comment by apachano** [comment]
No, definitely not critical right now. Although I added it as a stretch item (mostly to remind myself to add it as a low priority issue when this closes out).
