### ISSUE TITLE
Add sub menus to escape menu

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#196]
## Story
The escape menu should have a sub menu for input editing and settings.
We may do this in 0.3 and use it to put our new UI systems to the test. 

## MVP
What are the minimum features needed for this story?
-  [ ] Add sub menu for input editing
-  [ ] Add sub menu for adjusting settings

**Comment by apachano** [comment]
@tobyplowy This is half done, can we close this out and create a new issue for adding the input map editing?

**Comment by apachano** [comment]
Actually #176 is that issue, closing this
