### ISSUE TITLE
Make settings be remembered when changed in game.  

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#197]
## MVP
-  [ ] Make settings be remembered if changed in game.

**Comment by apachano** [comment]
This was already implemented a while ago

**Comment by tobyplowy** [comment]
It was? Why does it not save stuff then? Guess this is about to become a bug rapport then XD

**Comment by tobyplowy** [comment]
Let me do some testing around.

**Comment by apachano** [comment]
@tobyplowy Any update on your testing?

**Comment by tobyplowy** [comment]
Yeah sorry forgot. Seems to work somewhat. Some things like mouse sensitivity don't seem to get saved.

**Comment by apachano** [comment]
@tobyplowy Was this fixed with PR #331

**Comment by tobyplowy** [comment]
It was yeah.
