### ISSUE TITLE
Setup Travis CI for Linux & MacOS builds

### ISSUE THREAD

**Issue by DontBelieveMe** [GentenStudios/Phoenix#22]
Travis CI needs to be setup for this repository.
Should be fairly simple & just involve copying configuration files from QuartzEngine repository & fixing any build errors that occur on those platforms.
We should setup CI for the following environments:
 - Linux
      - GCC
     - Clang
- MacOS
     - GCC
     - Clang

It may make sense to figure out the minimum required compiler versions & build on them as well as latest/trunk

**Comment by DontBelieveMe** [comment]
Working on this atm (on feat-travis). Currently getting build errors as the GCC version under the current configuration does not support C++17. #24 addresses this.

**Comment by apachano** [comment]
Resolved by #31
