### ISSUE TITLE
Upgrade GCC & CMake Versions in Travis CI

### ISSUE THREAD

**Issue by DontBelieveMe** [GentenStudios/Phoenix#24]
We use C++17 and so need a minimum of GCC 7 for full support - current the distro Travis CI is configured to use only has 4.8.4 (I think - somewhere in the ~4 range) and so doesn't have the support we need.

Ideally we also should require CMake 3.13 across all platforms (required on Windows as only 3.13 supports Windows symlinks, but other platforms seem to do with just CMake 3.8 which has C++17 support).

 - [ ] Upgrade to use (min) GCC 7
 - [ ] Upgrade to use (min) clang version for C++17
 - [ ] Upgrade to use (min) CMake 3.13 for all platforms
 - [ ] Document minimum required dependency versions in `README.md`
    - [ ] GCC
    - [ ] Clang
    - [ ] CMake
    - [ ] MSVC/Visual Studio

**Comment by DontBelieveMe** [comment]
Just for the record, I believe this is what @M3TIOR is working on.

**Comment by tobyplowy** [comment]
@DontBelieveMe why did you assign yourself if you are not the one doing this?

**Comment by DontBelieveMe** [comment]
As it says in the timestamps, this was assigned to me long before someone else started working on it (because it was a task that I was going to do). As my comment above states I can't add them as a assignee so I'll keep it as me as I'll keep track of it & can merge it in/review it/whatever.

**Comment by apachano** [comment]
@DontBelieveMe If a non-org member comments on the issue we can assign it to them. Regardless I think @beeperdeeper089 has this resolved now we PR #31 . Can we close this or do we still have work to do?

**Comment by apachano** [comment]
Depreciated, we now use Azure
