### ISSUE TITLE
Audio stuck at 0,0,0

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#247]
## Describe the bug
The audio that should follow the player is stuck at 0,0,0

## To Reproduce
1. Go to 0,0,0
2. Break Block and observe loud sound
3. Go to 0,5,0
4. Break Block and observe quieter sound

## Expected behavior
Sound when a block is broken should emit from the block relative to the player's location

## Additional context
Introduced in #243

**Comment by tobyplowy** [comment]
I was going to report this. Guess you beat me to it =D

**Comment by apachano** [comment]
Closing as we stripped openAL from the code
