### ISSUE TITLE
Rename Sandbox project to Phoenix.

### ISSUE THREAD

**Issue by DontBelieveMe** [GentenStudios/Phoenix#25]
Currently the folder structure is
```
Engine/
  - "Engine" source code.
Sandbox/
  - Playground for testing whatevers in the engine.
```
But since we're focusing more on the game aspect, we should rename `Sandbox` to `Phoenix` (folder, cmake targets etc...).
The new `Phoenix` folder will contain all specific game code & `Engine` can continue to store "engine" code, anything that is not 100% game specific.
E.g.
 - Chunk rendering or maths library might go in `Engine/`

but
 -  Player code or code for handling mods specific to this game would go in `Phoenix`

**Comment by apachano** [comment]
Didn't we just refactor and create a new repo to eliminate having to worry about an engine/ game distinction while we created something functional? It feels like that work was for nothing if we revert that decision this early.

Also, we want to make sure chunk rendering also ends up in Pheonix as Quartz won't know what a chunk or even a voxel is. Remember the purpose of Quartz was so the code could be re-used to create non-voxel games.

**Comment by DontBelieveMe** [comment]
I'm not proposing moving anything around, literally just renaming the Sandbox folder to Phoenix - as it's not going to be a sandbox, it'll be a game. Called phoenix. This is the same as we decided earlier - the "Engine" folder does not represent a general engine that could be reused, but the engine that powers Phoenix. The separation is there to make the code more organised, that's all.

**Comment by apachano** [comment]
@DontBelieveMe I'm mostly curious what benefit we get from separating enginelike vs not so enginelike code. The majority of the code will live inside the Engine portion of things with the final implementation living inside the Game portion? In addition, at some point, there will be an engine distinction when Quartz is implemented (Leading to Phoenix depending on Phoenix Engine depending on Quartz Engine?), we also need to consider the distinction between the server and client (when that eventually comes up).

At the very least I think we should outline and document what goes inside each + the criteria for determining that in the future so everyone is on the same page as we are developing.

**Comment by apachano** [comment]
Postscript: I am all for refactoring the Sandbox folder to match our project's code name, I think it makes a lot more sense. I just want to make sure we are making solid and well thought out decisions that align with our product and target.
