### ISSUE TITLE
Improve base mod lua format. 

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#264]
## Story
Right now a simple block needs it's name 10 times to be able to register a block. Obviously this is a bit much, I would like to see a format like mintests block registration format but with some changes. 

Maybe something like this (I have no idea if this is not proper Lua or not. )

voxel.block.register("core:dirt", {
    displayname = "Dirt",
    textures = {"default_dirt.png"},
})

## MVP
What are the minimum features needed for this story?
-  [ ] make base mod Lua format more like the above.

**Comment by apachano** [comment]
Not an issue, this is already possible as the argument for registration is just a table and can be defined inline.
