### ISSUE TITLE
Display item in inventories = false

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#268]
## Story
Some items/blocks are not meant to be accessed by players and are instead meant to be set models or debug blocks/items. 
You really don't want these to be accessible by normal means hence why there needs to be a "Display item in inventories = false (True by default)" this would be added to blocks/items so that inventory/GUI mods can filter these items out more easily.

## MVP
-  [ ] Add display item in inventories = false/true (if this function is not present then it's true by default) function.

**Comment by apachano** [comment]
@tobyplowy This should be easy, but i'm curious what the purpose of an item that isn't in an inventory is?

**Comment by tobyplowy** [comment]
Well now that blocks use items to be able to place the block this is not super useful anymore.
But lets say you have an item and a block. You want to use an item to place said block instead of an actual block. 
You hide the block item. Or you have a block that's decorative only (Useless unless used in a specific way E.g a block with a big sail)
A mod may use said block for a generated building or something but may not want a player to get a hold of this block as it can be really odd out of context. (Context = where it was meant to be used)

**Comment by apachano** [comment]
I think that is implemented by default since you can create a block without creating an item. Are we okay to close this?

**Comment by tobyplowy** [comment]
Yup.
