### ISSUE TITLE
Segfault After Clicking on the Blank Game Screen

### ISSUE THREAD

**Issue by zicklag** [GentenStudios/Phoenix#269]
## Context

I'm building the game in a "Docker" container on my host using [udocker](https://github.com/indigo-dc/udocker) because I don't have root access on my build machine to install dependencies using `apt` so this may not be a bug worth addressing unless you can reproduce it on your own machine.

I used an Ubuntu 20.04 base docker image and installed CMake, g++, and the packages that Cmake complained about needing during the build.

**Commit:** ece10094e6436b

## Describe the bug

Segfault when clicking after the game appears to have loaded, but there is nothing on the screen other than imgui and the crosshair.

## To Reproduce

When starting up the game I:

- Am presented with the Genten Studio logo splash image
- The game starts and I can see the imgui promp and a screen crosshair with now graphics behind it:

![image](https://user-images.githubusercontent.com/25393315/88465680-554ade00-ce8a-11ea-8559-243ea1e1df32.png)

- As soon as I click the program segfaults:

**Log:**

```
[INFO][LOGGING] A log file was not specified, logging only to console.
[INFO][MODULE] Load mod 1
[INFO][MODULE] Load mod 3
[INFO][MODULE] Load mod 2
[INFO][MAIN] Registering world
[INFO][MAIN] Prepare rendering
[INFO][MAIN] Register GUI
[INFO][MAIN] Game layer attached
```

**Stacktrace:**

```
phx::ActorSystem::action1(entt::basic_registry<entt::entity>*, entt::entity) (/home/zicklag/git/other/Phoenix/Phoenix/ThirdParty/entt/src/entt/entity/sparse_set.hpp:357)
phx::client::Game::onEvent(phx::events::Event&) (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Game.cpp:410)
phx::gfx::LayerStack::onEvent(phx::events::Event) (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Graphics/LayerStack.cpp:159)
phx::client::Client::onEvent(phx::events::Event) (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Client.cpp:115)
phx::gfx::Window::dispatchToListeners(phx::events::Event&) (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Graphics/Window.cpp:323)
phx::gfx::Window::pollEvents() (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Graphics/Window.cpp:163)
phx::client::Client::run() (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Client.cpp:147)
main (/home/zicklag/git/other/Phoenix/Phoenix/Client/Source/Main.cpp:41)
__libc_start_main (@__libc_start_main:64)
_start (@_start:15)
```

## Expected behavior

No crash! :wink:

## Environment/System (please complete the following information)

-  Host OS: Pop!_OS 20.04
-  Container OS: Ubuntu 20.04
-  Application version: v0.2-dev
-  Commit: ece10094e6436b
-  Compiler: GCC 9.3.0

**Comment by beeperdeeper089** [comment]
First, long time no see!

I will try reproduce this in the morning, my first thoughts are the world may not actually be being generated.

Ping for @apachano since there's a good chance this could be related to the server architecture we've begun to roll in and us forgetting something on the client side.

**Comment by zicklag** [comment]
Hey @beeperdeeper089. It's been a while for sure. :slightly_smiling_face:

Good job with the progress so far you guys.

**Comment by apachano** [comment]
Hmm, I have a hunch this is the map not initializing but I'm not sure where. I'mma take a look now to see if I can follow where the logic is missing something.

**Comment by apachano** [comment]
Oh! actually, develop is hard-coded for multiplayer right now. Without the server it will segfault when it doesn't get data. I'm going to add some better error handling now but if you change the bool networked to false in the Game constructor then it should work.

**Comment by apachano** [comment]
Or launch the server before you launch the client

**Comment by zicklag** [comment]
Cool, if I just hardcode networked to false in the game constructor I can see the game, but it still segfaults when I click with the same stacktrace.

Either way, that's about all the time I have for now to test but it verifies that I can build it which is good. :slightly_smiling_face:

**Comment by tobyplowy** [comment]
@zicklag The clicking crash should be resolved. 
Issue resolved?

**Comment by zicklag** [comment]
I'll try it again soon.
