### ISSUE TITLE
Scaling window aspect squashes image. 

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#318]
## Describe the bug
When you change the size of the phoenix window it squashes the aspect of the rendered frames. 

## To Reproduce
1. Launch
2. Re scale window in whatever way (NOTE extremes are more noticeable)
3. PROFIT!

## Expected behavior
The aspect of the rendered image should always be non distorted. (Imagine playing Phoenix on an ultra wide screen with this bug XD)

## Screenshots
![image](https://user-images.githubusercontent.com/16853304/102019460-04258300-3d74-11eb-9046-9a9746c5612d.png)
![image](https://user-images.githubusercontent.com/16853304/102019497-3931d580-3d74-11eb-9969-de3cb474657f.png)

## Environment/System (please complete the following information)
-  OS: windows 10

**Comment by beeperdeeper089** [comment]
haha
