### ISSUE TITLE
Items and Inventories

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#34]
## Story
We need a system to handle items as well as inventories.

## MVP
- [ ] Items should be implemented with a similar registry system to blocks
    - [ ] Items can be registered via a static function
    - [ ] Universal data is stored only once
- [ ] Inventories should be able to be created in various sizes
- [ ] Items should be placeable in an inventory slot
- [ ] The player object should have an inventory slot dedicated to what is in hand

## Stretch
What are some non-required features for this story?
- [ ] We need to be able to interface with the inventory via a GUI
- [ ] Inventories should be able to load/ save when accessed
- [ ] Items have optional and definable functions triggered when actions are taken while an item is in hand

**Comment by tobyplowy** [comment]
@apachano You may wanna split up this issue?
Also the GUIs for 0.3 will be hard coded so you may wanna represent that.
