### ISSUE TITLE
Missing message in Lua panic handler

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#360]
## Describe the bug
When lua throws a panic after attempting to call a nil value, no message is supplied to CustomPanicHandler in ModManager.cpp. The default message handler gets the error message.

## To Reproduce
1. Add a nil function call to a lua file (ex add `core.print("message")` as this doesn't actually exist as a registered function
2. Run game and observe generic error
3. Comment out panic handler registration in ModManager.cpp `m_luaState.set_panic(
	    sol::c_call<decltype(&CustomPanicHandler), &CustomPanicHandler>);`
4. Run again and observe default panic handler throws verbose error

## Expected behavior
We should be getting the same error as the default panic handler

## Additional context
Last occurred in commit a1adf386

**Comment by apachano** [comment]
Possibly related: https://github.com/ThePhD/sol2/issues/965

**Comment by JosiahWI** [comment]
#361 fixes this issue.
