### ISSUE TITLE
Escape menu

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#37]
## Story
When the player hits the configured pause button, an escape menu is pulled up

## MVP
What are the minimum features needed for this story?
- [x] Pressing Escape pulls up a menu and frees the mouse
- [ ] The escape key is the default key but the escape action should be a mapped input
- [ ] The escape menu has a button to return to the game
- [ ] The escape menu has a button to end the game

## Stretch
What are some non-required features for this story?
- [ ] The escape menu has a sub-menu that allows editing settings
- [ ] The escape menu has a sub-menu that allows editing key mapping

**Comment by M3TIOR** [comment]
The base logic for some of this already exists, assign me, assign me! :smile:

**Comment by M3TIOR** [comment]
Yaaaaaaay!

**Comment by apachano** [comment]
After a discussion, we decided we want to implement a super rudimentary GUI system in-house for v 0.2 so we can get better items support + iterate on that functionality out of the gate. It may be worth considering this blocked by #99

**Comment by M3TIOR** [comment]
Aight

**Comment by tobyplowy** [comment]
@M3TIOR Are you still interested in this? 
If so you may wanna look at doing #99 first.

**Comment by tobyplowy** [comment]
This task is done right?

**Comment by beeperdeeper089** [comment]
Yeah

**Comment by apachano** [comment]
I mean the MVP wasn't really completed and the current escape button is a very glitchy button. Please create an issue for every bullet point that was missed.

**Comment by tobyplowy** [comment]
@apachano What points were missed? Also isn't the current escape menu a temp?
I think it will do until we have a more proper system in place. V0.3 is getting GUI systems right? Maybe we can do it then?

**Comment by apachano** [comment]
Then maybe we create this issue again and tag it with 0.3?

**Comment by apachano** [comment]
The escape button does not have a button to return to the game, not any of the stretch tasks.

**Comment by tobyplowy** [comment]
Ah yeah. Mind making said issue?

**Comment by tobyplowy** [comment]
I'm not sure how I would write it out, otherwise I would do it =D
