### ISSUE TITLE
Update License to 2020

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#50]
## Story
Happy 2020

## MVP
- [ ] All license copies in all files are updated to include 2020 date
- [ ] All doxy file documentation is updated to include 2020 date

**Comment by apachano** [comment]
nudge nudge @tobyplowy nudge

**Comment by tobyplowy** [comment]
@apachano I'm on it! Will see what I can do.

**Comment by beeperdeeper089** [comment]
After a quick google, I've came across these:

[StackOverflow post on this issue](https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year)

[Another post on another site](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/)

**Comment by apachano** [comment]
So the format on all files created in 2019 would be 2019 - 2020 while the format for all files created in 2020 would just be 2020.

**Comment by beeperdeeper089** [comment]
Should we just set them all to 2019-2020 because if we automate it it'll be an actrual pain?
