### ISSUE TITLE
pressing enter in the debug console with an empty text field posts nothing.

### ISSUE THREAD

**Issue by tobyplowy** [GentenStudios/Phoenix#58]
## Describe the bug
It seems like it's possible to post literally nothing in the debug console by just pressing enter in the text edit box.

## To Reproduce
1. Go to debug console.
2. Press enter without typing anything...

## Expected behavior
It should not allow you to post anything unless there is text in the text field.

**Comment by tobyplowy** [comment]
@M3TIOR Ping ;D

**Comment by M3TIOR** [comment]
You should remove this, it's not a bug, it's a feature.

**Comment by tobyplowy** [comment]
Mmk...
