### ISSUE TITLE
Add sound functionality

### ISSUE THREAD

**Issue by apachano** [GentenStudios/Phoenix#89]
## Story
We need an OpenAL API abstraction to play various sound files at various times.

## MVP
What are the minimum features needed for this story?
- [x] Implement function to play a sound
- [x] Implement function to loop a sound
- [x] Implement function to end said sound loop
- [ ] Implement method to get active sounds
- [x] Play random sound from a list of sounds (will be used for footstep sounds and such)
- [x] Expose ability to trigger sound to lua
- [x] Expose ability to loop sound to lua
- [x] Expose ability to end sound loop to lua

## Stretch
What are some non-required features for this story?
- [ ] Implement background music system

- [ ] Lua can call currently playing sounds for events (If sound "core.dirtstep" is playing kill "player")
- [ ] Implement dynamic distortion based on environment system (For example sounds sound more dampened underwater/echos in caves)

**Comment by tobyplowy** [comment]
Maybe when you register a sound you can set the type.
Music, footstep, mob, place/break, other.
That way you can fine tune what's louder and what's not as loud.

**Comment by apachano** [comment]
I would argue that when you play a sound, you supply the volume. Also, if a position is supplied, then play at that position, if it's not supplied, play for the current player.

**Comment by tobyplowy** [comment]
@apachano I meant this would be controlled by the end user. (Player not modder)
Lets say you wanna turn down foot steps but increase ambient sounds and music and placing and removing sounds. There has to be some easy way to control some of these categories without going into all your mods one by one to fine tune everything.

**Comment by apachano** [comment]
Makes sense
